version: "3"

services:
  client:
    build:
      context: .
    container_name: farm-client
    env_file:
      - .env
  minio:
    image: minio/minio:RELEASE.2022-03-17T06-34-49Z
    container_name: minio
    ports:
    - "9000:9000"
    - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin_password"
    command:
    - "server"
    - "/data/"
    - "--console-address"
    - ":9001"
    volumes:
      - minio:/data/

volumes:
  minio:
